remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pagina para Repositorio
description: Essa pagina tem o objetivo de ser um repositorio de arquivo online e de facil acesso
